version: '3.8'

services:
  ubuntu_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qmcpack_container_AMD
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: -1
    #          capabilities: [gpu]
    #runtime: nvidia
    working_dir: /app
    # Optional port mapping (uncomment if your app needs it)
    ports:
      - "8000:8000"
      - "80:80"
      - "3000:3000"
      - "6000:6000"

    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["tail", "-f", "/dev/null"]
